const configtext = [
//0 Japanese
{
title:"冥鳴ひまりVSサキュバスシューティング 旧ゲーム開発ログになります。",
hvs0:"Himari Meimei VS Succubus 旧ゲーム開発ログになります。",
hvs1:"遊ぶ方はこちらから ",
hvs2:"冥鳴ひまり VS サキュバス ",
hvs3:"シューティングゲーム ",
hvs4:"新しいゲーム開発ログはItch.ioに記録してますので、そちらをご覧くださいませ。 ",
hvs5:"またお会いしましょうボイスの作り直し",
hvs6:"こんにちは私はめいめいひまりですに作り直し",
hvs7:"JSONにトライ処理を追加する",
hvs8:"アニメーションの修正。太ももの方向を調整",
hvs9:"翻訳全般（ボイスを下部に実装）",
hvs10:"翻訳を下部に実装",
hvs11:"スマホ翻訳を別に実装",
hvs12:"トップ画面にも翻訳を追加する（これでゲームは終了です。お疲れ様でした）",
hvs13:"スキル効果バフにより、レベルデザイン調整",
hvs14:"字幕のフォントサイズ調整",
hvs15:"エンディング前に字幕入れるため、エンディングに入る時間を遅らせる",
hvs16:"アイテムショップ中に字幕が出ない不具合",
hvs17:"エンディング後にGOTOPを押すと、ボイスが2個鳴る不具合",
hvs18:"サウンドからの処理をループからにする。サウンドの不具合を解決",
hvs19:"QWER使用中の際にスキルレベルのフォントの不具合を解決",
hvs20:"エンディングに入る前にボイスが止まる不具合（timerの問題）",
hvs21:"9月14日",
hvs22:"トップ画面のランキングを翻訳",
hvs23:"トップ画面上の言語別フォントサイズ調整",
hvs24:"QWER下部フォントサイズを調整",
hvs25:"トップ画面を右から表示する言語に対応",
hvs26:"リザルト画面にて右から表示する言語に対応",
hvs27:"エンディング翻訳",
hvs28:"UI翻訳",
hvs29:"アイテムショップを翻訳",
hvs30:"アイテムショップ内での右から読む言語の不具合を解消",
hvs31:"ステージナンバーとポーズのフォント言語別調整",
hvs32:"9月13日",
hvs33:"ボイス翻訳",
hvs34:"ボイスを一度英訳",
hvs35:"エンディングを一度英訳",
hvs36:"リザルトを翻訳（Ranked Numberだけ）",
hvs37:"エンディングで言語を取得しない不具合を修正",
hvs38:"コンフィグのフォント言語別調整",
hvs39:"9月12日",
hvs40:"タッチジェスチャーになる問題を解決。F12の開発者ツール由来でした",
hvs41:"タッチパネルつきノートの切り替えの不具合を解消",
hvs42:"メイン画面のボイスをスムースに調整。呼吸と、短く",
hvs43:"ボイス制作（スムースにつながる用に調整）",
hvs44:"ボイスの整理",
hvs45:"ゲーム開始時にサウンドの多用で、ゲームパッドで敵の弾が早くなる不具合を解消",
hvs46:"9月11日",
hvs47:"フランス語の初期設定をJSOＮある場合はそれを使うよう仕様変更",
hvs48:"9月10日",
hvs49:"JSONの追加実装（ Config Data, Language, Result Ranking, Clearedf )",
hvs50:"French Keyboardにて、キー入力とマウスとの干渉を解決",
hvs51:"France語で、マウスクリック押せない、色が変わらない等の不具合を解決",
hvs52:"コンフィグ画面で、MouseDragが選択できない不具合を解消",
hvs53:"9月9日",
hvs54:"入力方法を変更すると、設定が初期化される事案を解消",
hvs55:"リザルトでキー入力で移動できない。マウスとの干渉を解決",
hvs56:"WASDにて死んだ後に右側に急ぐ不具合を解消",
hvs57:"タイマーが進んでいて、最初にボスが出てくる不具合を解決",
hvs58:"銃が押しっぱなしになる不具合。呼び出し順を入れ替えて解決",
hvs59:"低画質の背景が変わらない不具合。JSONの呼び出し方を変更して解決",
hvs60:"コンフィグ操作の一部が描画されない不具合。JSONの呼び出し方を変更して解決",
hvs61:"トップ画面のボタンが連打される事案を解消",
hvs62:"リザルト画面とトップ画面とアイテムショップ内で、",
hvs63:"マウスとの干渉でWASDやゲームパッドで動かせない不具合を解決",
hvs64:"スペシャルサンクスの修正。スペシャルサンクスもゲームパッドで動きます",
hvs65:"コンフィグにJSON11個使ってるのを2個に減らしたい。２個にはなりませんでした。",
hvs66:"エンディングにトランスレーションの追加",
hvs67:"金メダルのトリコロールの色の順番を修正",
hvs68:"ゲームパッドでサブマシンガンの音が鳴らない不具合を修正",
hvs69:"リザルト画面にて範囲外をクリックする不具合を修正",
hvs70:"トップ画面にて、十字キーを使う人にとって、Zボタンでゲームを始めれない不具合を修正",
hvs71:"エンディング画像をたくさん描画する不具合を修正",
hvs72:"フランス語はJSONでセーブしても再ロードされる問題を解決",
hvs73:"ボスのスキル変更ができない",
hvs74:"鬼モンスターの調整",
hvs75:"アイテムショップに入るとタイマーが０になる事案を修正",
hvs76:"敵が出なくなるバグ。多分直ってるかも",
hvs77:"アイテムショップで、お金が不足しても購入できる事案が発生",
hvs78:"死んだ後に発射しない銃の音が鳴り続ける事案を解消",
hvs79:"ボスを倒した後、コンフィグに入るとBGMがボスに戻るという事案を解消 ",
hvs80:"ロボのビームバグを調整",
hvs81:"急に長いまま発射される",
hvs82:"途中で止まる",
hvs83:"なぜかビームを発射したまま上下に動く",
hvs84:"途中で止まる。そして連射する",
hvs85:"発射しなくなる",
hvs86:"アサルトライフルに切り替わらない",
hvs87:"キャラの当たり判定の作り直し",
hvs88:"AA",
hvs89:"Q",
hvs90:"W",
hvs91:"E",
hvs92:"R",
hvs93:"エンディングの実装",
hvs94:"デバッグモードの追加",
hvs95:"無限バリア（シューティングのレベルデザインに疲れてしまったため）",
hvs96:"全スキル＋１（シューティングのレベルデザインに疲れてしまったため）",
hvs97:"低スペックモードの実装",
hvs98:"モブ１",
hvs99:"モブ２",
hvs100:"モブ３",
hvs101:"モブ４",
hvs102:"モブ５",
hvs103:"モブ６",
hvs104:"モブ７",
hvs105:"モブ８",
hvs106:"モブ９",
hvs107:"モブ１０",
hvs108:"衝突判定",
hvs109:"キャラクターアニメーションの作り直し",
hvs110:"服のふち",
hvs111:"腕のふち",
hvs112:"手のふち",
hvs113:"スカートのふち",
hvs114:"スカート裏のふち",
hvs115:"タイツのふち",
hvs116:"足靴のふち",
hvs117:"髪の塗り",
hvs118:"服の塗り",
hvs119:"腕の塗り",
hvs120:"手の塗り",
hvs121:"スカートの塗り",
hvs122:"スカート裏の塗り",
hvs123:"タイツの塗り",
hvs124:"足靴の塗り",
hvs125:"左手ふち",
hvs126:"左手塗り",
hvs127:"首元塗り",
hvs128:"スカート横リボンふち",
hvs129:"スカート横リボン塗り",
hvs130:"新アニメ化",
hvs131:"爽快感と頭痛にならないレベルデザイン",
hvs132:"8月28日",
hvs133:"唇が灰色なんですが…なぜ！",
hvs134:"これを修正する場合は画像編集ソフトで１枚１枚コピペして結合して私の指が痙攣しますね",
hvs135:"いい感じに進んでるのは間違いありません",
hvs136:"あと、１週間前後でゲームは完成予定",
hvs137:"キャラクターアニメーションの作り直し",
hvs138:"JSONの追加実装（ Config Data, Language, Result Ranking )",
hvs139:"エンディング",
hvs140:"翻訳全般（英語になってる部分とボイスを下部に実装）",
hvs141:"画質と低スペックモードの実装",
hvs142:"爽快感といい感じのフラストレーションなレベルデザイン",
hvs143:"finally!",
hvs144:"8月23日",
hvs145:"France Keyboard 配列対応（これは一旦止める判断してましたが、再度入れ直すことにしました）",
hvs146:"Smart Phone 入力",
hvs147:"    プレレンダリング",
hvs148:"    処理",
hvs149:"    描画",
hvs150:"Game Pad 入力",
hvs151:"GUIの入力",
hvs152:"アイテムショップをAny Deviceで入力する",
hvs153:"リザルトのマウスの入力画面",
hvs154:"サブ制作",
hvs155:"  アイテムショップを開きやすく",
hvs156:"  アイテムショップBUYの範囲を大きくする",
hvs157:"  アイテムショップの出口を大きくする",
hvs158:"  キーボードでポーズ  ミュート  コンフィグ処理を可能にする",
hvs159:"  画質クオリティーの設定",
hvs160:"ボスの移動ルーチン",
hvs161:"QWERの名前変わっても描画する",
hvs162:"QWERの入力設定を変えても入力可能にする",
hvs163:"一部のモンスターの連射を遅くしました。",
hvs164:"爽快感とちょうどいいストレスと頭痛にならないレベル調整",
hvs165:"バグ対応",
hvs166:"ミュートオンにしてコンフィグに入って戻ったら音が鳴るバグ修正",
hvs167:"ポーズしてQを使って戻った後に、ポーズができなくなる事象が発生",
hvs168:"ポーズボタン押して長時間経って戻ると処理が重くなっている事象が発生",
hvs169:"警備ロボの判定を再修正",
hvs170:"十字キー入力  スキルボタンを表示されない",
hvs171:"死ぬとアサルトの音になる",
hvs172:"バリアーが外れないバグが発生  バリア時間2秒～2.8秒",
hvs173:"アイテムショップのヒット判定の下部がクリックできない事象が発生",
hvs174:"ゲーム画面に入ってすぐにポーズを押される事象が発生",
hvs175:"ポーズ中に動けてしまう不具合が発生",
hvs176:"WASDと十字キーで弾が連射になる",
hvs177:"スキルを打って死ぬと、スキルが止まってリスタート後に発射される",
hvs178:"長時間ポーズ中後に１面のボスが出てきてしまった。ポーズ後に処理が重くなる事象が発生",
hvs179:"ポーズで雲が止まってない事象が発生",
hvs180:"トップ画面にきらきら星を入れる。（入れてみましたが、目がチカチカするので取り消しました。）",
hvs181:"ポーズボタンをキャンセルキー（Esc, Skill1, Del, Back Space）で解除できるようにしました。",
hvs182:"8月18日",
hvs183:"制作中",
hvs184:"ボスの移動ルーチン",
hvs185:"Game Pad 入力",
hvs186:"Smart Phone 入力",
hvs187:"キャラクターアニメーションの作り直し",
hvs188:"France Keyboard 配列対応（これは一旦止める判断してましたが、再度入れ直すことにしました）",
hvs189:"JSONの追加実装（ Config Data, Language, Result Ranking )",
hvs190:"エンディング",
hvs191:"翻訳全般（英語になってる部分とボイスを下部に実装）",
hvs192:"画質と低スペックモードの実装",
hvs193:"爽快感といい感じのフラストレーションなレベルデザイン",
hvs194:"finally!",
hvs195:"8月16日",
hvs196:"BGM編集  及び切り替え実装",
hvs197:"  BGMの読み込み",
hvs198:"  BGMからちょうちょ",
hvs199:"  ちょうちょからBGM",
hvs200:"  BGMからボス",
hvs201:"  ボスからBGM",
hvs202:"アイテムショップの出る時間",
hvs203:"  ３０秒",
hvs204:"  ９０秒",
hvs205:"  死んだ分だけ短くなる",
hvs206:"ちょうちょで自動コイン集め",
hvs207:"  ちょうちょ画像編集",
hvs208:"  ちょうちょ画像取込",
hvs209:"  ちょうちょプレレンダリング",
hvs210:"  ちょうちょ処理",
hvs211:"  ちょうちょ描画",
hvs212:"  ちょうちょの出る時間",
hvs213:"  ４５秒",
hvs214:"敵を倒すごとにCD短くなる",
hvs215:"  ５秒に１回CD半減",
hvs216:"  １０秒に１回２体湧き",
hvs217:"Mob吹き出し移植",
hvs218:"  プレレンダリング",
hvs219:"  処理",
hvs220:"  描画１",
hvs221:"  描画２",
hvs222:"ショップのキャンセリングバグ。キャンセルボタンを使う",
hvs223:"続けてくれてありがとうのボイス追加",
hvs224:"ボスを倒した後の処理",
hvs225:"アイテムショップのバグ修正",
hvs226:"敵のゴールドドロップ実装",
hvs227:"敵のHP実装",
hvs228:"敵のルーチンタイプ",
hvs229:"8月10日",
hvs230:"アニメーションを実装しようとしましたが、その前にデモを上げたいです。巻き髪も同時制作中 ",
hvs231:"Qスキルのタイミング調整",
hvs232:"味方スキル移植",
hvs233:"  プレレンデリング",
hvs234:"    リアルタイム",
hvs235:"    移植",
hvs236:"    当たり",
hvs237:"      Q",
hvs238:"      W",
hvs239:"      E",
hvs240:"      R",
hvs241:"Dead Anime",
hvs242:"  キャラクター死亡演出遅延  黒弾幕のリスタート",
hvs243:"バイブレーションボタン入力変更",
hvs244:"  バイブレーション試験",
hvs245:"  Config  バイブオンオフ",
hvs246:"リザルト画面の追加",
hvs247:"  Score表示  獲得賞金額",
hvs248:"モブ攻撃実装",
hvs249:"  プレレンデリング",
hvs250:"  リアルタイム",
hvs251:"  描画",
hvs252:"    ボスアニメーション",
hvs253:"    当たり",
hvs254:"    BOSS1の仕様変更する",
hvs255:"リザルト画面の追加  獲得賞金額  倒したモンスターの数  与ダメージ",
hvs256:"アイテムショップ実装",
hvs257:"8月3日",
hvs258:"死亡演出方法を変えてみました。いい感じです",
hvs259:"現在制作中：リザルト画面の追加  獲得賞金額  倒したモンスターの数  与ダメージ",
hvs260:"7月28日",
hvs261:"7月27日",
hvs262:"やや作る量を増やしすぎてる感が否めませんが、まあいいでしょう",
hvs263:"Dead Animation キャラクター死亡遅延演出    ",
hvs264:"黒弾幕のリスタート",
hvs265:"Config バイブオンオフ バイブレーション試験",
hvs266:"7月25日",
hvs267:"リザルト画面の追加  獲得賞金額  倒したモンスターの数  与ダメージ",
hvs268:"ちょうちょでコイン集め",
hvs269:"ドローンショップを移行",
hvs270:"味方スキルを移行",
hvs271:"敵の攻撃を移行",
hvs272:"Mob吹き出しを移行",
hvs273:"ここでデモを公開できると思います",
hvs274:"7月24日",
hvs275:"敵の攻撃パターン無事終了しました。 ",
hvs276:"新キャラを試行錯誤中。立ち絵に合わせて、キャラクターをアップデート中。",
hvs277:"ちょっと頭のてっぺん大きいかな。あと目が小さい。顔のＥラインが甘い ",
hvs278:"敵の攻撃パターンを現在作ってます。画像はのせるほどでもありませんが、とりあえず４体できました",
hvs279:"敵は１１体出る予定なのであと７体です",
hvs280:"7月13日",
hvs281:"敵の攻撃パターン  ルーチンをプログラミングしてます ",
hvs282:"7月9日",
hvs283:"調子を崩してましたが、やや回復したので制作を再開",
hvs284:"オンライン実習室というYOUTUBEのライブはとても興味深い。",
hvs285:"周りの人たちが勉強、在宅、家事、創作と作業して共感できる",
hvs286:"余談をしましたが、スキルのエフェクトはできました。",
hvs287:"まずはグレネード ",
hvs288:"ウルトです",
hvs289:"死亡エフェクトです ",
hvs290:"Configは一応完成。ただ処理が重いことがちょっと心配。スマホは動くのかな",
hvs291:"Config",
hvs292:"・Touch Gestures入力",
hvs293:"・バイブレーション試験",
hvs294:"6月24日",
hvs295:"けっこう進んだぞ！Game Pad終了したのやばい！嬉しい！",
hvs296:"カスタマイズの表示方法変更処理  終了",
hvs297:"フランス語キーボード配列AZERTY対応  処理不足のため断念",
hvs298:"QWER入力  終了",
hvs299:"十字キー入力  終了",
hvs300:"Game Pad  終了",
hvs301:"言語をゲームパッド、キーボードで変更する  終了",
hvs302:"6月27日",
hvs303:"コンフィグ内容の入力はできたので、処理と描画する",
hvs304:"設定画面入ると画面が最大化しちゃうんだ！",
hvs305:"翻訳の追加。トップ画面とボイス内容２６ワード＊３３言語",
hvs306:"簡易入力設定の入れ替え",
hvs307:"6月20日",
hvs308:"スマホゲーやんないからわかんないけど、こんな感じの入力で合ってるかな？ ",
hvs309:"お買い物はいつだって楽しい。ここの店員元はおじさんだったんだ",
hvs310:"翻訳をがんばりました。ただ、文字がはみ出てるのと、",
hvs311:"GUIをきれいに行を揃えたいなと思います。明日はもっと進むといいな。 ",
hvs312:"6月19日",
hvs313:"Monster から Charaへの攻撃",
hvs314:"Score表示  獲得賞金額",
hvs315:"ここでデモ版公開できるかと思います。",
hvs316:"エンドロール作成",
hvs317:"Mob吹き出しの微調整",
hvs318:"アニメーション追加",
hvs319:"真上移動  真下移動",
hvs320:"斜め上移動  斜め下移動",
hvs321:"死亡時のAnimationを追加します。",
hvs322:"何もしてない時の状態のアニメーションを追加します。",
hvs323:"トップ画面の飾りつけ",
hvs324:"7月19日",
hvs325:"終了タスク",
hvs326:"翻訳作業をスクリプトに埋め込み完了",
hvs327:"吹き出しに台詞を埋め込みましたが、左右の幅がうまくいきませんでした。",
hvs328:"33言語と、言語によって文字の横幅に差分あり、処理できませんでした。",
hvs329:"33言語の処理は困難とし、ChatGPTの提案で吹き出しは固定のまま進めることにしました。 ",
hvs330:"6月9日",
hvs331:"こちらはVOICE VOX 冥鳴ひまりさんを使用しています。",

},

//1 English
{
title:"Himari Meimei VS Succubus: This is the development log for the original game.",
hvs0:"Himari Meimei VS Succubus: This is the development log for the original game.",
hvs1:"Click here to play",
hvs2:"Himari Meimei VS Succubus",
hvs3:"Shoot 'Em Up game",
hvs4:"I’m posting the development log for my new game on Itch.io, so please check it out there.",
hvs5:"Reworking the “See You Again” voice line",
hvs6:"Reworking the “Hello, I’m Himari Meimei” line",
hvs7:"Adding a try statement to the JSON",
hvs8:"Animation fixes: Adjusted the direction of the thighs",
hvs9:"General translation (implemented voice lines at the bottom)",
hvs10:"Implemented translations at the bottom",
hvs11:"Implemented separate translations for mobile",
hvs12:"Added translations to the title screen (This concludes the game. Great job!)",
hvs13:"Adjusted level design based on skill effect buffs",
hvs14:"Adjusted subtitle font size",
hvs15:"Delayed the transition to the ending to allow for subtitles before it begins",
hvs16:"Fixed a bug where subtitles didn’t appear in the item shop",
hvs17:"Fixed a bug where pressing GOTOP after the ending played two voice lines",
hvs18:"Changed sound processing to a loop. Resolved sound issues",
hvs19:"Fixed a font issue with skill levels while using QWER",
hvs20:"Fixed a bug where voice lines stopped before the ending (Timer issue)",
hvs21:"September 14",
hvs22:"Translated the rankings on the main menu",
hvs23:"Adjusted font sizes by language on the main menu",
hvs24:"Adjusted the font size at the bottom of the QWER keys",
hvs25:"Added support for languages that read from right to left on the main menu",
hvs26:"Added support for languages that read from right to left on the results screen",
hvs27:"Translated the ending",
hvs28:"Translated the UI",
hvs29:"Translated the item shop",
hvs30:"Fixed a bug with languages that read from right to left in the item shop",
hvs31:"Adjusted the font for stage numbers and the “Pause” button by language",
hvs32:"September 13",
hvs33:"Voice Translation",
hvs34:"Translate voice once into English",
hvs35:"Translate the ending once into English",
hvs36:"Translate results (Ranked Number only)",
hvs37:"Fixed a bug where the language was not detected in the ending",
hvs38:"Adjusted font settings by language in the configuration",
hvs39:"September 12",
hvs40:"Resolved an issue causing touch gestures. This was caused by the F12 developer tools.",
hvs41:"Fixed a bug with switching between laptops with touchscreens.",
hvs42:"Adjusted the voice on the main screen to sound smoother with breathing and shorter phrases.",
hvs43:"Voice production (adjusted for smooth transitions)",
hvs44:"Organized voice files",
hvs45:"Fixed a bug where excessive sound effects at the start of the game caused \n\nenemy bullets to move faster when using a gamepad",
hvs46:"September 11",
hvs47:"Changed the specification for French default settings to use JSON if available",
hvs48:"September 10",
hvs49:"Implemented additional JSON features (Config Data, Language, Result Ranking, Clearedf)",
hvs50:"Resolved interference between key input and the mouse on the French keyboard",
hvs51:"Resolved issues in French, such as being unable to click the mouse or colors not changing",
hvs52:"Resolved an issue where “MouseDrag” could not be selected in the configuration screen",
hvs53:"September 9",
hvs54:"Settings reset when changing the input method",
hvs55:"Character movement on the Results screen blocked by mouse input when using the keyboard",
hvs56:"Character rushing to the right after dying while using WASD",
hvs57:"Boss appearing at the start despite the timer still running",
hvs58:"Gun remaining held down; resolved by reordering the call sequence",
hvs59:"Low quality background not updating; resolved by changing the JSON call method",
hvs60:"Some configuration settings not being displayed; resolved by changing the JSON loading method.",
hvs61:"Rapid tapping of main menu buttons",
hvs62:"Issues on the Results screen, main menu, and item shop",
hvs63:"where WASD or gamepad controls were unresponsive due to mouse interference",
hvs64:"Fixed the “Special Thanks” section. The “Special Thanks” section now works with the gamepad",
hvs65:"I wanted to reduce the number of JSON files used in the configuration from 11 to 2. \n\nI wasn’t able to reduce it to 2.",
hvs66:"Added translations to the ending.",
hvs67:"Corrected the color order of the tricolor on the gold medal.",
hvs68:"Missing submachine gun sound when using a gamepad",
hvs69:"Error triggered by clicking outside the designated area on the Results screen",
hvs70:"Inability to start the game with the Z button on the main menu when using the directional pad",
hvs71:"Excessive rendering of ending images",
hvs72:"Resolved an issue where French text would be reloaded even after saving as JSON",
hvs73:"Unable to change boss skills",
hvs74:"Adjusted the Demon Monster",
hvs75:"Item shop entry resetting the timer to zero",
hvs76:"Enemies no longer appearing (possibly fixed)",
hvs77:"Item shop purchases possible despite insufficient funds",
hvs78:"Non-firing gun sound continuing after death",
hvs79:"BGM reverting to the boss theme when opening the config menu after defeating a boss",
hvs80:"Adjusted the robot beam bug",
hvs81:"Beam suddenly fires and remains active for a long time",
hvs82:"Beam stops midway",
hvs83:"For some reason, the robot moves up and down while the beam is still firing",
hvs84:"Beam stops midway, then fires rapidly",
hvs85:"Beam stops firing altogether",
hvs86:"Does not switch to the assault rifle",
hvs87:"Reworked character collision detection",
hvs88:"AA",
hvs89:"Q",
hvs90:"W",
hvs91:"E",
hvs92:"R",
hvs93:"Implemented the ending",
hvs94:"Added debug mode",
hvs95:"Infinite barrier (because I got tired of designing shooting levels)",
hvs96:"All skills +1 (because I got tired of designing shooting levels)",
hvs97:"Implemented low-spec mode",
hvs98:"Mob 1",
hvs99:"Mob 2",
hvs100:"Mob 3",
hvs101:"Mob 4",
hvs102:"Mob 5",
hvs103:"Mob 6",
hvs104:"Mob 7",
hvs105:"Mob 8",
hvs106:"Mob 9",
hvs107:"Mob 10",
hvs108:"Collision detection",
hvs109:"Reworked character animations",
hvs110:"Clothing outlines",
hvs111:"Arm outlines",
hvs112:"Hand outlines",
hvs113:"Skirt outlines",
hvs114:"Skirt lining outlines",
hvs115:"Tights outlines",
hvs116:"Shoes outlines",
hvs117:"Hair shading",
hvs118:"Clothing shading",
hvs119:"Arm shading",
hvs120:"Hand shading",
hvs121:"Skirt shading",
hvs122:"Skirt lining shading",
hvs123:"Tights shading",
hvs124:"Shoes shading",
hvs125:"Left hand outlines",
hvs126:"Left Hand Shading",
hvs127:"Neck Shading",
hvs128:"Side Skirt Ribbon Edge",
hvs129:"Side Skirt Ribbon Shading",
hvs130:"New Animation",
hvs131:"Level Design That’s Both Thrilling and Doesn’t Give You a Headache",
hvs132:"August 28",
hvs133:"The lips are gray… why?!",
hvs134:"If I have to fix this, I’ll have to copy and paste each frame one by one in image editing software and \n\nmerge them my fingers are going to start twitching.",
hvs135:"There’s no doubt things are progressing nicely",
hvs136:"Also, the game is scheduled to be completed in about a week",
hvs137:"Reworking character animations",
hvs138:"Implementing additional JSON (Config Data, Language, Result Ranking)",
hvs139:"Ending",
hvs140:"General translation (implementing English text and voice lines at the bottom)",
hvs141:"Implementing image quality and low-spec mode",
hvs142:"Level design that strikes a balance between a sense of exhilaration and \n\njust the right amount of frustration",
hvs143:"Finally!",
hvs144:"August 23",
hvs145:"Support for French keyboard layouts (I had decided to put this on hold for now, \n\nbut I’ve decided to re-implement it)",
hvs146:"Smartphone input",
hvs147:"    Pre-rendering",
hvs148:"    Processing",
hvs149:"    Rendering",
hvs150:"Game Pad Input",
hvs151:"GUI Input",
hvs152:"Navigating the Item Shop with “Any Device”",
hvs153:"Mouse Input Screen in the Results Menu",
hvs154:"Sub-Features",
hvs155:"  Make it easier to open the Item Shop",
hvs156:"  Enlarge the “BUY” area in the Item Shop",
hvs157:"  Enlarge the exit from the Item Shop",
hvs158:"  Enable Pause, Mute, and Config functions via keyboard",
hvs159:"  Graphics Quality Settings",
hvs160:"Boss Movement Routine",
hvs161:"Continue rendering even if the QWER keys are remapped",
hvs162:"Ensure input remains possible even if QWER input settings are changed",
hvs163:"Slowed down the rapid-fire attacks of certain monsters.",
hvs164:"Adjusted difficulty to strike a balance between a sense of exhilaration, \n\njust the right amount of challenge, and a level that doesn’t cause headaches",
hvs165:"Bug Fixes",
hvs166:"Sound playing after returning from the configuration menu with Mute enabled",
hvs167:"Unable to pause again after resuming with the Q key",
hvs168:"Performance slowdown after resuming from a long pause",
hvs169:"Re-adjusted the collision detection for security robots",
hvs170:"D-pad input: Skill buttons are not displayed",
hvs171:"When you die, the Assault sound plays",
hvs172:"A bug occurred where the barrier wouldn’t disappear; barrier duration is 2–2.8 seconds",
hvs173:"An issue occurred where the bottom part of the item shop’s hitbox couldn’t be clicked",
hvs174:"An issue occurred where the pause button was pressed immediately upon entering the game screen",
hvs175:"A bug occurred where you could move while paused",
hvs176:"Rapid-fire occurs with WASD and the D-pad",
hvs177:"If you die while using a skill, the skill stops and is fired after restarting",
hvs178:"The Stage 1 boss appeared after a long pause. Performance becomes sluggish after resuming from pause",
hvs179:"Clouds do not stop moving while paused",
hvs180:"Added “Twinkle Twinkle Little Star” to the title screen. (I tried adding it, \n\nbut removed it because it caused eye strain.)",
hvs181:"Made it possible to cancel the pause using the cancel keys (Esc, Skill 1, Del, Backspace).",
hvs182:"August 18",
hvs183:"In Development",
hvs184:"Boss movement routine",
hvs185:"Game Pad Input",
hvs186:"Smartphone Input",
hvs187:"Reworking character animations",
hvs188:"Support for French keyboard layouts (I had decided to put this on hold for now, \n\nbut I’ve decided to reimplement it)",
hvs189:"Additional JSON implementation (Config Data, Language, Result Ranking)",
hvs190:"Ending",
hvs191:"General translation (Implemented English text and voice lines at the bottom)",
hvs192:"Implementation of high-quality graphics and low-spec modes",
hvs193:"Level design that strikes a good balance between a sense of exhilaration and \n\njust the right amount of frustration",
hvs194:"Finally!",
hvs195:"August 16",
hvs196:"BGM Editing and Transition Implementation",
hvs197:"  Loading BGM",
hvs198:"  Butterfly from BGM",
hvs199:"  BGM from Butterfly",
hvs200:"  Boss from BGM",
hvs201:"  BGM from Boss",
hvs202:"Item Shop Appearance Intervals",
hvs203:"  30 seconds",
hvs204:"  90 seconds",
hvs205:"  Interval shortens by the number of times you die",
hvs206:"Automatic Coin Collection with Butterflies",
hvs207:"  Butterfly Image Editing",
hvs208:"  Importing Butterfly Images",
hvs209:"  Butterfly Pre-rendering",
hvs210:"  Butterfly Processing",
hvs211:"  Butterfly Rendering",
hvs212:"  Butterfly Appearance Time",
hvs213:"  45 seconds",
hvs214:"Cooldown shortens with each enemy defeated",
hvs215:"  Cooldown halved once every 5 seconds",
hvs216:"  Two enemies spawn once every 10 seconds",
hvs217:"Mob Speech Bubble Port",
hvs218:"  Pre-rendering",
hvs219:"  Processing",
hvs220:"  Rendering 1",
hvs221:"  Rendering 2",
hvs222:"Fixed the shop cancellation bug. Use the cancel button",
hvs223:"Added a “Thank you for continuing” voice line",
hvs224:"Post-boss-defeat processing",
hvs225:"Fixed a bug in the item shop",
hvs226:"Implemented enemy gold drops",
hvs227:"Implemented enemy HP",
hvs228:"Enemy routine types",
hvs229:"August 10",
hvs230:"I tried to implement animations, but I want to upload a demo first. \n\nI’m also working on the curly hair at the same time",
hvs231:"Adjusted Q skill timing",
hvs232:"Ported ally skills",
hvs233:"  Pre-rendering",
hvs234:"    Real-time",
hvs235:"    Porting",
hvs236:"    Hit detection",
hvs237:"      Q",
hvs238:"      W",
hvs239:"      E",
hvs240:"      R",
hvs241:"Dead Anime",
hvs242:"  Delay in character death animations  Restart of black bullet barrage",
hvs243:"Changed vibration button input",
hvs244:"  Vibration test",
hvs245:"  Config  Turn vibration on/off",
hvs246:"Added results screen",
hvs247:"  Score display  Prize money earned",
hvs248:"Implemented mob attacks",
hvs249:"  Pre-rendering",
hvs250:"  Real-time",
hvs251:"  Rendering",
hvs252:"    Boss animations",
hvs253:"    Hit effects",
hvs254:"    Change BOSS1 specifications",
hvs255:"Added Results Screen  Prize Amount  Number of Monsters Defeated  Damage Dealt",
hvs256:"Implemented Item Shop",
hvs257:"August 3",
hvs258:"I changed the character death animation. It looks good.",
hvs259:"Currently in development: Added Results Screen Prize \n\nAmount Number of Monsters Defeated Damage Dealt",
hvs260:"July 28",
hvs261:"July 27",
hvs262:"I can’t deny that I might have taken on a bit too much, but oh well.",
hvs263:"Dead Animation: Character Death Delay Effect",
hvs264:"Restarted work on the black bullet curtain",
hvs265:"Config: Vibration On/Off – Vibration testing",
hvs266:"July 25",
hvs267:"Added results screen: Prize money earned, Number of monsters defeated, Damage dealt",
hvs268:"Collecting coins with butterflies",
hvs269:"Migrated the drone shop",
hvs270:"Migrated ally skills",
hvs271:"Migrated enemy attacks",
hvs272:"Migrated mob speech bubbles",
hvs273:"I think I can release a demo here now",
hvs274:"July 24",
hvs275:"Successfully finished the enemy attack patterns.",
hvs276:"I’m currently experimenting with a new character. \n\nI’m updating the character design to match the stand-alone illustration.",
hvs277:"The top of the head might be a little too big. Also, \n\nthe eyes are small. The E-line of the face isn’t defined enough.",
hvs278:"I’m currently working on the enemy attack patterns. \n\nThe images aren’t quite ready to share yet, but I’ve managed to create four so far.",
hvs279:"There are supposed to be 11 enemies in total, so I have seven more to go.",
hvs280:"July 13",
hvs281:"I’m programming the routines for the enemy attack patterns.",
hvs282:"July 9",
hvs283:"I’d been feeling under the weather, but I’ve recovered a bit, so I’ve resumed development.",
hvs284:"The “Online Lab” YouTube livestream is really interesting.",
hvs285:"I can relate to the people around me who are studying, working from home, \n\ndoing chores, or creating things.",
hvs286:"That was a bit of a tangent, but I’ve finished the skill effects.",
hvs287:"First up: the grenade.",
hvs288:"Here’s the ultimate move.",
hvs289:"And here’s the death effect.",
hvs290:"The config is more or less complete. I’m a little worried it might be a bit resource-intensive, \n\nthough. I wonder if it’ll run on a smartphone.",
hvs291:"Config",
hvs292:"・Touch Gestures input",
hvs293:"・Vibration testing",
hvs294:"June 24",
hvs295:"I’ve made quite a bit of progress! Finishing the gamepad support is amazing! I’m so happy!",
hvs296:"Process for changing customization display method Completed",
hvs297:"Support for French AZERTY keyboard layout Abandoned due to insufficient processing power",
hvs298:"QWER input Completed",
hvs299:"D-pad input Completed",
hvs300:"Game Pad Completed",
hvs301:"Changing language via gamepad or keyboard Completed",
hvs302:"June 27",
hvs303:"I’ve entered the config data, so now I just need to handle the processing and rendering.",
hvs304:"The screen maximizes when I enter the settings menu!",
hvs305:"Added translations. Main menu and voice lines: 26 words × 33 languages",
hvs306:"Switched out the simplified input settings",
hvs307:"June 20",
hvs308:"I don’t play mobile games, so I’m not sure, but is this kind of input correct?",
hvs309:"Shopping is always fun. The clerk here used to be an older guy.",
hvs310:"I worked hard on the translations. However, some text is overflowing, and",
hvs311:"I’d like to align the GUI text neatly. I hope to make more progress tomorrow.",
hvs312:"June 19",
hvs313:"Attack from Monster to Chara",
hvs314:"Score display Prize money earned",
hvs315:"I think I’ll be able to release a demo version here.",
hvs316:"Create end credits",
hvs317:"Fine-tune mob speech bubbles",
hvs318:"Add animations",
hvs319:"Move straight up Move straight down",
hvs320:"Move diagonally up Move diagonally down",
hvs321:"Add a death animation.",
hvs322:"Add an animation for the idle state.",
hvs323:"Decorate the main menu screen",
hvs324:"July 19",
hvs325:"Completed Tasks",
hvs326:"Finished embedding translations into the script.",
hvs327:"I embedded dialogue into the speech bubbles, but the width didn’t work out right.",
hvs328:"With 33 languages, there are differences in character width depending on the language, \n\nso I couldn’t handle it.",
hvs329:"Since handling 33 languages proved difficult, \n\nI decided to proceed with fixed-width speech bubbles as suggested by ChatGPT.",
hvs330:"June 9",
hvs331:"I’m using Himari Meimei from VOICE VOX for this.",

}

];
